version: 2

# Source Definition for Raw Data
sources:
  - name: public
    tables:
      - name: online_retail
        columns:
          - name: InvoiceNo
            data_tests:
              - not_null
          - name: CustomerID
            data_tests: []  # Add a not_null test if you expect CustomerID to always be present

# Models Definition for Customer and Product Focused Models
models:
  - name: stg_online_retail_product_focused
    description: "Product-focused model allowing NULL CustomerID and duplicate InvoiceNo"
    columns:
      - name: InvoiceNo
        data_tests:
          - not_null

  - name: stg_online_retail_sales
    description: "Model for sales transactions with positive quantities"
    columns:
      - name: InvoiceNo
        data_tests:
          - not_null
          - unique
      - name: CustomerID
        data_tests:
          - not_null

  - name: stg_online_retail_returns
    description: "Model for return transactions with negative quantities"
    columns:
      - name: InvoiceNo
        data_tests:
          - not_null
          - unique
      - name: CustomerID
        data_tests:
          - not_null

  - name: analytics_customer_summary
    description: "Summary of total sales, returns, and net value per customer"
    columns:
      - name: CustomerID
        description: "Unique identifier for each customer"
        tests:
          - not_null
      - name: total_sales_value
        description: "Total value of sales for the customer"
        tests:
          - not_null
      - name: total_returns_value
        description: "Total value of returns for the customer"

  - name: analytics_monthly_summary
    description: "Summary of total sales, returns, and net value per month"
    columns:
      - name: month
        description: "Month of the transaction"
        tests:
          - not_null
      - name: total_sales_value
        description: "Total value of sales for the month"
        tests:
          - not_null

  - name: analytics_country_summary
    description: "Summary of total sales, returns, and net value per country"
    columns:
      - name: Country
        description: "Country where the transaction occurred"
        tests:
          - not_null
      - name: total_sales_value
        description: "Total value of sales for the country"
        tests:
          - not_null
